#
# To build a Conda package, run conda build as:
#
#    env GITREV=<git sha, tag, or branch> conda build .
#
# Example:
#
#    env GITREV=1.5.9 conda build .
#

package:
  name: doxygen
  version: {{ environ.get('GIT_DESCRIBE_TAG', '') + (('_%s' % environ['GIT_DESCRIBE_NUMBER']) if environ.get('GIT_DESCRIBE_NUMBER', '0') != '0' else '') }}

build:
  script_env:
    - GITREV

source:
  git_rev: {{ environ['GITREV'] }}
  git_url: https://github.com/LSST/doxygen

requirements:
  build:
    - python
    - eups

  run:
    - python

about:
  home: https://github.com/LSST/doxygen
#  license: GPLv2
#  summary: A version manager tracking product dependencies
